### ISSUE TITLE
Cannot edit note

### ISSUE THREAD

**Issue by mplorentz** [noffle/hyperpad-desktop#1]
I followed the build instructions but when I run I'm presented with a note that I cannot seem to edit. I am running macOS 10.13.3 and I tried node v8.10.10 and v9.11.1.
<img width="1280" alt="screen shot 2018-04-06 at 12 24 23 pm" src="https://user-images.githubusercontent.com/1165004/38432677-4beb422c-3996-11e8-9216-9fec9b0aef67.png">

**Comment by hackergrrl** [comment]
Looks like a crash. Is there an error in the Console tab if you open the developer tools? I think it's `Cmd+Option+i`.

**Comment by mplorentz** [comment]
It shows this error:
```
/Users/matt/dev/hyperpad-desktop/node_modules/bindings/bindings.js:88 Uncaught Error: The module '/Users/matt/dev/hyperpad-desktop/node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/Users/matt/dev/hyperpad-desktop/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/Users/matt/dev/hyperpad-desktop/node_modules/leveldown/leveldown.js:4:46)
```

I don't know much about node. I tried `npm rebuild` and `npm install`, as well as blowing away my `node_modules` folder and following the installation instructions again, but got the same error.

**Comment by mplorentz** [comment]
I figured it out. I had to run: 

`npm install --save-dev electron-rebuild`

and:

`./node_modules/.bin/electron-rebuild`

As detailed in [this stackoverflow post](https://stackoverflow.com/questions/42616008/node-module-version-conflict-when-installing-modules-for-electron)

**Comment by hackergrrl** [comment]
Thanks for documenting this. I'm using `electron-rebuild` now as of 45ef419f96d4ff9f6d116563c5458f6f76bde187
